# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Inspiration
description: >- # this means to ignore newlines until "baseurl:"
url: "https://inspirationmobility.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: manoverboard-alpha
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
sass:
  sass_dir: _sass
  style: compressed
collections_dir: collections

# pagination
# https://jekyllrb.com/docs/pagination/
paginate: 27
paginate_path: "/news/page-:num/"

# archives
# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled: 
    - categories
  layout: archive
  permalinks:
    category: '/archive/:name/'


# CloudCannon Options
_options:
  image: # Front matter field
    uploads_dir: "uploads"
  layout:
    hidden: true
  content:
    uploads_dir: "uploads"
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    link: true
    blockquote: true
    numberedlist: true
    bulletedlist: true
    embed: true
    image: true

# CloudCannon Field Descriptions
_comments:
  title: This will show up in the browser tab, and is used for SEO purposes.
  their_testimonial_text: Quotations are automatically inserted.
  custom_latest_posts: This will show the three newest posts marked as 'featured' in the News.
  featured_post: When custom latest posts is true on the Home page, this post will show instead of the most recent News post.

# Collections (Custom Post Types)
# https://jekyllrb.com/docs/collections/
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  general-pages:
    output: true
    _hide_content: true
  top-level-pages:
    output: true
    _hide_content: true
  testimonials:
    output: false
    _hide_content: true
  case-studies:
    output: true
    _hide_content: true
    permalink: /case-study/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "general-pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "form-pages"
    values:
      layout: "page-notransition"
  - scope:
      path: ""
      type: "top-level-pages"
    values:
      layout: "top-level-page"
  - scope: 
      path: ""
      type: "case-studies"
    values:
      layout: "case-study"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
